### ISSUE TITLE
Prevent keyboard input from going to `iex`?

### ISSUE THREAD

**Issue by nathanl** [LeToteTeam/input_event#8]
For a specific keyboard plugged into my Nerves device, I'd like to interpret the keypresses as events for my program. This works, but I also see the keystrokes show up in `iex`.

Can I somehow capture these events and prevent them from going to `iex`?

![no_idea](https://user-images.githubusercontent.com/338814/49655481-c6652580-fa08-11e8-9db9-c75f71dc9962.png)

**Comment by fhunleth** [comment]
lol - no one ever attaches gifs to any of my projects. 

I'm pretty sure the fix is to have input_event grab the device. Try adding the following line

```
ioctl(fd, EVIOCGRAB, (void*) 1);
```

at https://github.com/LeToteTeam/input_event/blob/master/src/input_event.c#L205. 

It would be nice to make a function/check errors/tidy up the code, but I think that should do it.

I have to leave shortly, but I'll see if I can check it out some time this weekend.

**Comment by nathanl** [comment]
Thanks for the response! 😄 I'll try this as soon as I get a chance to tinker again.

**Comment by Xeronel** [comment]
Is there any chance of getting this added to the project as an optional param or separate function call that can be made from elixir?

**Comment by fhunleth** [comment]
@Xeronel Yes, definitely! How do you feel about editing the C code to add the `ioctl` call? If you're comfortable enough to give it a try and let me know that it works, I'll clean up the C if necessary and get it merged. If not, then no worries, next time that I use a Pi4 w/ Scenic, I'll give it a try. I don't do this all that often so please be patient with me, but I think that I'll have an opportunity in the next 2-3 weeks.

**Comment by fhunleth** [comment]
Second thought is that we could post to the #nerves channel on the Elixir lang slack. Someone else might want this feature as well and might help make the change.

**Comment by fhunleth** [comment]
Forgot to close this as fixed. It's fixed in https://github.com/nerves-web-kiosk/input_event/releases/tag/v1.1.0.
